blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    path("all_articles/", views.AllArticles.as_view(), name="all_articles"),
    path("article/<int:pk>", views.ArticleDetail.as_view(), name="article_detail"),
    path("categories", views.CategoryList.as_view(), name="categories"),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path("", lambda r: redirect("/blog/")),
    path("blog/", include("blog.urls")),
    path("admin/", admin.site.urls),
]

blog/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=500)
    icon = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name}: {self.description}"

class Tag(models.Model):
    title = models.CharField(max_length=200)

    def __str__(self):
        return self.title

class Article(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    text = models.TextField()
    publication_date = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(default=False)
    category = models.ManyToManyField(Category)
    image = models.URLField(blank=True, null=True)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return f"{self.title} by {self.author}"


class Comment(models.Model):
    text = models.TextField()
    author = models.CharField(max_length=200)
    publication_date = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="comments")

    def __str__(self):
        return f"Comment to {self.article.title}"

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from blog.models import Article, Category


# def index(request):
#     return render(request, "blog/index.html")


class Index(ListView):
    model = Article
    template_name = "blog/index.html"

    def get_queryset(self):
        return Article.objects.order_by("-publication_date")[:3]

class AllArticles(ListView):
    model = Article
    template_name = "blog/all_articles.html"

class ArticleDetail(DetailView):
    model = Article

class CategoryList(ListView):
    model = Category
    template_name = "blog/categories.html"

blog/templates/base.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <title>
        {% block title %}
            my blog
        {% endblock %}
    </title>
    <script src="https://kit.fontawesome.com/dc5bced0a2.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
</head>
<body>
    <main>{% block content %}{% endblock %}</main>
</body>
</html>

blog/templates/blog/all_articles.html
{% extends 'base.html' %}

{% block title %}
    all articles
{% endblock %}

{% block content %}

<h2>All Articles</h2>

{% include "blog/article_list.html" %}



{% endblock %}

blog/templates/blog/article_detail.html
{% extends 'base.html' %}

{% block title %}
    {{article.title}}
{% endblock %}

{% block content %}

    <div>
        <div>
            <h1>{{article.title}}</h1>
            <h2>Author: {{article.author}}</h2>
            <h3>Categories</h3>
            <ul>
                {% for category in article.category.all %}
                    <li>
                        <a href="{% url 'categories' %}">
                            {{category.name}}
                            <i class="{{category.icon}}"></i>
                        </a>
                    </li>
                {% endfor %}
            </ul>
            {% if article.image %}
                <img src="{{article.image}}" alt="none" width="300" height="300">
            {% endif %}
            <p>{{article.text}}</p>
            <p>{{article.publication_date}}</p>
            <p>
                Tags:
                {% for tag in article.tags.all %}
                    {{ tag.title }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </p>
        </div>

        <div>
            <h3>Comments</h3>
            {% for comment in article.comments.all %}
            <div class="comment">
                <span class="comment_author">{{comment.author}}</span><br>
                {{comment.text}}<br>
                <span class="date">{{comment.publication_date}}</span><br>
                <p></p>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

blog/templates/blog/article_list.html
<ul>
    {% for article in article_list %}
    <li>
        <a href="{% url 'article_detail' article.id %}">{{ article.title }} ({{article.publication_date}})
        </a>
    </li>
    {% empty %}
    <li>There is no articles</li>
    {% endfor %}
</ul>

blog/templates/blog/base.html
<!DOCTYPE html>
<html>
<head>
    <title>My Blog</title>
</head>
<body>
    <header><h1>My Blog</h1></header>
    <main>{% block content %}{% endblock %}</main>
</body>
</html>

blog/templates/blog/categories.html
{% extends 'base.html' %}

{% block title %}
    categories
{% endblock %}

{% block content %}

    <h2>Categories</h2>

    <ul>
        {% for category in category_list %}
            <li>
                <div>
                    {{category.name}}
                    <i class="{{category.icon}}"></i>
                </div>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Latest articles</h2>

{% include "blog/article_list.html" %}

{% if article_list %}
    <h3><a href="{% url 'all_articles' %}">for more click here</a></h3>
{% endif %}

{% endblock %}